name: Lint and Test
inputs:
  SA_PASSWORD:
    required: true
    default: abcdefgh1!
runs:
  using: "composite"
  steps:
    - name: Set up Node
      uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # v2.5.1
      with:
        node-version: '16'
        check-latest: true
        registry-url: 'https://www.myget.org/F/ed-fi/npm/'

    - name: Install
      run: yarn install
      shell: bash

    - name: Setup tmate session
      uses: mxschmitt/action-tmate@8b4e4ac71822ed7e0ad5fb3d1c33483e9e8fb270 # v3.1.1
