nodeLinker: node-modules

npmRegistryServer: "https://www.myget.org/F/ed-fi/npm/"
npmScopes:
  edfi:
    npmRegistryServer: "https://www.myget.org/F/ed-fi/npm/"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
