// SPDX-License-Identifier: Apache-2.0
// Licensed to the Ed-Fi Alliance under one or more agreements.
// The Ed-Fi Alliance licenses this file to you under the Apache License, Version 2.0.
// See the LICENSE and NOTICES files in the project root for more information.

import {
  DomainEntityBuilder,
  DomainEntityExtensionBuilder,
  DomainEntitySubclassBuilder,
  DescriptorBuilder,
  EnumerationBuilder,
  MetaEdTextBuilder,
  NamespaceBuilder,
  type Enhancer,
  newMetaEdEnvironment,
  newPluginEnvironment,
} from '@edfi/metaed-core';
import type { MetaEdEnvironment, Namespace, SchoolYearEnumeration, TopLevelEntity } from '@edfi/metaed-core';
import {
  domainEntityReferenceEnhancer,
  descriptorReferenceEnhancer,
  domainEntityExtensionBaseClassEnhancer,
  domainEntitySubclassBaseClassEnhancer,
} from '@edfi/metaed-plugin-edfi-unified';
import { enhance as entityPropertyApiSchemaDataSetupEnhancer } from '../../src/model/EntityPropertyApiSchemaData';
import { enhance as entityApiSchemaDataSetupEnhancer } from '../../src/model/EntityApiSchemaData';
import { enhance as namespaceSetupEnhancer } from '../../src/model/Namespace';
import { enhance as apiPropertyMappingEnhancer } from '../../src/enhancer/ApiPropertyMappingEnhancer';
import { enhance as apiEntityMappingEnhancer } from '../../src/enhancer/ApiEntityMappingEnhancer';
import { enhance as propertyCollectingEnhancer } from '../../src/enhancer/PropertyCollectingEnhancer';
import { enhance as resourceNameEnhancer } from '../../src/enhancer/ResourceNameEnhancer';
import { enhance as apiSchemaBuildingEnhancer } from '../../src/enhancer/ApiSchemaBuildingEnhancer';
import { enhance as openApiRequestBodyComponentEnhancer } from '../../src/enhancer/OpenApiRequestBodyComponentEnhancer';
import { enhance as openApiReferenceComponentEnhancer } from '../../src/enhancer/OpenApiReferenceComponentEnhancer';
import { enhance as resourceDomainEnhancer } from '../../src/enhancer/ResourceDomainEnhancer';
import { enhance as jsonSchemaForInsertEnhancer } from '../../src/enhancer/JsonSchemaForInsertEnhancer';
import { enhance as referenceComponentEnhancer } from '../../src/enhancer/ReferenceComponentEnhancer';
import { enhance as allJsonPathsMappingEnhancer } from '../../src/enhancer/AllJsonPathsMappingEnhancer';
import { enhance as mergeJsonPathsMappingEnhancer } from '../../src/enhancer/MergeJsonPathsMappingEnhancer';
import { enhance as mergeDirectiveEqualityConstraintEnhancer } from '../../src/enhancer/MergeDirectiveEqualityConstraintEnhancer';
import { enhance as identityFullnameEnhancer } from '../../src/enhancer/IdentityFullnameEnhancer';
import { enhance as subclassIdentityFullnameEnhancer } from '../../src/enhancer/SubclassIdentityFullnameEnhancer';
import { enhance as identityJsonPathsEnhancer } from '../../src/enhancer/IdentityJsonPathsEnhancer';
import { enhance as documentPathsMappingEnhancer } from '../../src/enhancer/DocumentPathsMappingEnhancer';
import { enhance as queryFieldMappingEnhancer } from '../../src/enhancer/QueryFieldMappingEnhancer';
import { enhance as typeCoercionJsonPathsEnhancer } from '../../src/enhancer/TypeCoercionJsonPathsEnhancer';
import { createResourceFragment, enhance } from '../../src/enhancer/OpenApiResourceFragmentEnhancer';
import { NamespaceEdfiApiSchema } from '../../src/model/Namespace';
import { OpenApiDocumentType } from '../../src/model/api-schema/OpenApiDocumentType';
import type { JsonPath } from '../../src/model/api-schema/JsonPath';
import type { OpenApiFragment } from '../../src/model/api-schema/OpenApiFragment';
import type { Operation, Parameter } from '../../src/model/OpenApiTypes';
import { metaEdPluginEnhancers } from '../integration/PluginHelper';

/**
 * OpenAPI operation methods generated by the resource fragment enhancer.
 */
type OpenApiOperationMethod = 'get' | 'post' | 'put' | 'delete';

const changeVersionParameterRefs: string[] = [
  '#/components/parameters/MinChangeVersion',
  '#/components/parameters/MaxChangeVersion',
];

const trackedChangeParameterRefs: string[] = [
  '#/components/parameters/MinChangeVersion',
  '#/components/parameters/MaxChangeVersion',
  '#/components/parameters/limit',
  '#/components/parameters/offset',
  '#/components/parameters/totalCount',
];

const cursorPagingParameterRefs: string[] = ['#/components/parameters/pageToken', '#/components/parameters/pageSize'];

/**
 * Returns an operation from a fragment path for focused OpenAPI assertions.
 */
function operationFrom(fragment: OpenApiFragment, path: string, method: OpenApiOperationMethod): Operation {
  const operation = fragment.paths?.[path]?.[method];
  expect(operation).toBeDefined();
  return operation as Operation;
}

/**
 * Returns component parameter references from an OpenAPI operation.
 */
function parameterRefsFrom(operation: Operation): string[] {
  return (operation.parameters ?? []).flatMap((parameter: Parameter) => ('$ref' in parameter ? [parameter.$ref] : []));
}

/**
 * Returns inline parameter names from an OpenAPI operation.
 */
function parameterNamesFrom(operation: Operation): string[] {
  return (operation.parameters ?? []).flatMap((parameter: Parameter) => ('name' in parameter ? [parameter.name] : []));
}

/**
 * Asserts an operation advertises live Change Query filter parameters.
 */
function expectLiveChangeVersionFilterParameters(operation: Operation): void {
  expect(parameterRefsFrom(operation)).toEqual(expect.arrayContaining(changeVersionParameterRefs));
}

/**
 * Asserts an operation does not advertise live Change Query filter parameters.
 */
function expectNoLiveChangeVersionFilterParameters(operation: Operation): void {
  const parameterRefs: string[] = parameterRefsFrom(operation);
  changeVersionParameterRefs.forEach((parameterRef: string) => expect(parameterRefs).not.toContain(parameterRef));
}

/**
 * Asserts an operation advertises only the tracked-change query parameters.
 */
function expectTrackedChangeQueryParameters(operation: Operation): void {
  const parameterRefs: string[] = parameterRefsFrom(operation);

  expect(parameterRefs).toEqual(trackedChangeParameterRefs);
  cursorPagingParameterRefs.forEach((parameterRef: string) => expect(parameterRefs).not.toContain(parameterRef));
  expect(parameterNamesFrom(operation)).toEqual([]);
}

/**
 * Asserts a tracked-change operation references the expected response item schema.
 */
function expectTrackedChangeResponseSchema(operation: Operation, trackedChangeItemSchemaName: string): void {
  expect(operation.responses['200']).toEqual({
    description: 'The requested Change Query results were successfully retrieved.',
    content: {
      'application/json': {
        schema: {
          type: 'array',
          items: {
            $ref: `#/components/schemas/${trackedChangeItemSchemaName}`,
          },
        },
      },
    },
  });
}

/**
 * Asserts an operation advertises a tracked-change response and query parameter contract.
 */
function expectTrackedChangeOperation(operation: Operation, trackedChangeItemSchemaName: string): void {
  expectTrackedChangeQueryParameters(operation);
  expectTrackedChangeResponseSchema(operation, trackedChangeItemSchemaName);
}

function runPrerequisiteEnhancers(metaEd: MetaEdEnvironment) {
  metaEdPluginEnhancers().forEach((pluginEnhancer: Enhancer) => pluginEnhancer(metaEd));
  namespaceSetupEnhancer(metaEd);
  entityPropertyApiSchemaDataSetupEnhancer(metaEd);
  entityApiSchemaDataSetupEnhancer(metaEd);
  referenceComponentEnhancer(metaEd);
  apiPropertyMappingEnhancer(metaEd);
  propertyCollectingEnhancer(metaEd);
  apiEntityMappingEnhancer(metaEd);
  jsonSchemaForInsertEnhancer(metaEd);
  allJsonPathsMappingEnhancer(metaEd);
  mergeJsonPathsMappingEnhancer(metaEd);
  mergeDirectiveEqualityConstraintEnhancer(metaEd);
  resourceNameEnhancer(metaEd);
  documentPathsMappingEnhancer(metaEd);
  identityFullnameEnhancer(metaEd);
  subclassIdentityFullnameEnhancer(metaEd);
  queryFieldMappingEnhancer(metaEd);
  identityJsonPathsEnhancer(metaEd);
  typeCoercionJsonPathsEnhancer(metaEd);
  resourceDomainEnhancer(metaEd);
  openApiRequestBodyComponentEnhancer(metaEd);
  openApiReferenceComponentEnhancer(metaEd);
}

/**
 * Creates a concrete resource whose identity metadata cannot derive public tracked-change key schemas.
 */
function concreteResourceWithoutPublicTrackedChangeKeyMetadata(): TopLevelEntity {
  return {
    type: 'domainEntity',
    metaEdName: 'Student',
    documentation: 'A student',
    allowPrimaryKeyUpdates: false,
    namespace: {
      namespaceName: 'EdFi',
      projectName: 'Ed-Fi',
      isExtension: false,
    },
    data: {
      edfiApiSchema: {
        endpointName: 'students',
        domains: [],
        identityJsonPaths: ['$.studentUniqueId' as JsonPath],
        queryFieldMapping: {},
        openApiReferenceComponent: {},
        openApiReferenceComponentPropertyName: '',
        openApiRequestBodyComponent: {
          type: 'object',
          properties: {
            id: {
              type: 'string',
            },
          },
        },
        openApiRequestBodyComponentPropertyName: 'EdFi_Student',
        openApiRequestBodyCollectionComponents: [],
      },
    },
  } as unknown as TopLevelEntity;
}

describe('OpenApiResourceFragmentEnhancer', () => {
  describe('when enhancing a domain entity', () => {
    const metaEd: MetaEdEnvironment = newMetaEdEnvironment();
    metaEd.plugin.set('edfiApiSchema', newPluginEnvironment());
    const namespaceName = 'EdFi';
    const domainEntityName = 'Student';
    let namespace: any = null;

    beforeAll(() => {
      MetaEdTextBuilder.build()
        .withBeginNamespace(namespaceName)
        .withStartDomainEntity(domainEntityName)
        .withDocumentation('A student')
        .withStringIdentity('StudentUniqueId', 'doc', '30', '20')
        .withBooleanProperty('Active', 'Is active', true, false)
        .withEndDomainEntity()
        .withEndNamespace()
        .sendToListener(new NamespaceBuilder(metaEd, []))
        .sendToListener(new DomainEntityBuilder(metaEd, []));

      domainEntityReferenceEnhancer(metaEd);
      runPrerequisiteEnhancers(metaEd);
      enhance(metaEd);

      namespace = metaEd.namespace.get(namespaceName);
    });

    it('should add openApiFragments to the entity data', () => {
      const student = namespace.entity.domainEntity.get('Student');
      const studentApiData = student.data.edfiApiSchema;

      expect(studentApiData).toBeDefined();
      expect(studentApiData.openApiFragments).toBeDefined();
      expect(studentApiData.openApiFragments[OpenApiDocumentType.RESOURCES]).toBeDefined();
    });

    it('should create a resources fragment with schemas, paths, and tags', () => {
      const student = namespace.entity.domainEntity.get('Student');
      const studentApiData = student.data.edfiApiSchema;
      const fragment = studentApiData.openApiFragments[OpenApiDocumentType.RESOURCES];

      expect(fragment).toBeDefined();
      expect(fragment?.components?.schemas).toBeDefined();
      expect(fragment?.components?.schemas?.EdFi_Student).toBeDefined();
      expect(fragment?.paths).toBeDefined();
      expect(fragment?.paths?.['/ed-fi/students']).toBeDefined();
      expect(fragment?.paths?.['/ed-fi/students/deletes']).toBeDefined();
      expect(fragment?.paths?.['/ed-fi/students/keyChanges']).toBeDefined();
      expect(fragment?.tags).toBeDefined();
      expect(fragment?.tags).toHaveLength(1);
      expect(fragment?.tags?.[0].name).toBe('students');

      const serializedFragment: string = JSON.stringify(fragment);
      expect(serializedFragment).not.toContain('Use-Snapshot');
      expect(serializedFragment).not.toContain('NotFoundUseSnapshot');
      expect(serializedFragment).not.toContain('snapshot');
      expect(fragment?.paths?.['/ed-fi/students']?.get?.responses['404']).toEqual({
        $ref: '#/components/responses/NotFound',
      });
      expect(fragment?.paths?.['/ed-fi/students/{id}']?.get?.responses['404']).toEqual({
        $ref: '#/components/responses/NotFound',
      });
      expect(fragment?.paths?.['/ed-fi/students']?.post?.responses['405']).toEqual({
        description: 'Method Is Not Allowed.',
      });
      expect(fragment?.paths?.['/ed-fi/students/{id}']?.put?.responses['405']).toEqual({
        description: 'Method Is Not Allowed.',
      });
      expect(fragment?.paths?.['/ed-fi/students/{id}']?.delete?.responses['405']).toEqual({
        description: 'Method Is Not Allowed.',
      });
    });

    it('should add live Change Query filters only to the GET-many operation', () => {
      const student = namespace.entity.domainEntity.get('Student');
      const studentApiData = student.data.edfiApiSchema;
      const fragment = studentApiData.openApiFragments[OpenApiDocumentType.RESOURCES] as OpenApiFragment;

      expectLiveChangeVersionFilterParameters(operationFrom(fragment, '/ed-fi/students', 'get'));
      expectNoLiveChangeVersionFilterParameters(operationFrom(fragment, '/ed-fi/students', 'post'));
      expectNoLiveChangeVersionFilterParameters(operationFrom(fragment, '/ed-fi/students/{id}', 'get'));
      expectNoLiveChangeVersionFilterParameters(operationFrom(fragment, '/ed-fi/students/{id}', 'put'));
      expectNoLiveChangeVersionFilterParameters(operationFrom(fragment, '/ed-fi/students/{id}', 'delete'));
    });

    it('should add tracked-change delete and key-change paths with response schemas', () => {
      const student = namespace.entity.domainEntity.get('Student');
      const studentApiData = student.data.edfiApiSchema;
      const fragment = studentApiData.openApiFragments[OpenApiDocumentType.RESOURCES] as OpenApiFragment;

      expectTrackedChangeOperation(
        operationFrom(fragment, '/ed-fi/students/deletes', 'get'),
        'EdFi_Student_TrackedChangeDelete',
      );
      expectTrackedChangeOperation(
        operationFrom(fragment, '/ed-fi/students/keyChanges', 'get'),
        'EdFi_Student_TrackedChangeKeyChange',
      );
      expect(fragment.paths?.['/ed-fi/students/deletes']?.['x-Ed-Fi-domains']).toEqual([]);
      expect(fragment.paths?.['/ed-fi/students/keyChanges']?.['x-Ed-Fi-domains']).toEqual([]);
    });

    it('should emit profile-compatible unprofiled tracked-change fragments', () => {
      const student = namespace.entity.domainEntity.get('Student');
      const studentApiData = student.data.edfiApiSchema;
      const fragment = studentApiData.openApiFragments[OpenApiDocumentType.RESOURCES] as OpenApiFragment;
      const collectionPath: string = '/ed-fi/students';
      const trackedChangeSchemaNames: string[] = Object.keys(fragment.components.schemas)
        .filter((schemaName: string) => schemaName.includes('_TrackedChange'))
        .sort();

      expect(fragment.paths?.[`${collectionPath}/deletes`]).toBeDefined();
      expect(fragment.paths?.[`${collectionPath}/keyChanges`]).toBeDefined();
      expect(fragment.paths?.[`${collectionPath}/{id}/deletes`]).toBeUndefined();
      expect(fragment.paths?.[`${collectionPath}/{id}/keyChanges`]).toBeUndefined();
      expect(fragment.paths?.['/availableChangeVersions']).toBeUndefined();
      expect(fragment.paths?.['/changeQueries/v1/availableChangeVersions']).toBeUndefined();
      expect(operationFrom(fragment, `${collectionPath}/deletes`, 'get').responses['200']).toMatchInlineSnapshot(`
        Object {
          "content": Object {
            "application/json": Object {
              "schema": Object {
                "items": Object {
                  "$ref": "#/components/schemas/EdFi_Student_TrackedChangeDelete",
                },
                "type": "array",
              },
            },
          },
          "description": "The requested Change Query results were successfully retrieved.",
        }
      `);
      expect(operationFrom(fragment, `${collectionPath}/keyChanges`, 'get').responses['200']).toMatchInlineSnapshot(`
        Object {
          "content": Object {
            "application/json": Object {
              "schema": Object {
                "items": Object {
                  "$ref": "#/components/schemas/EdFi_Student_TrackedChangeKeyChange",
                },
                "type": "array",
              },
            },
          },
          "description": "The requested Change Query results were successfully retrieved.",
        }
      `);
      expect(trackedChangeSchemaNames).toEqual([
        'EdFi_Student_TrackedChangeDelete',
        'EdFi_Student_TrackedChangeKey',
        'EdFi_Student_TrackedChangeKeyChange',
      ]);
      expect(fragment.components.schemas.EdFi_Student_TrackedChangeKey).toMatchInlineSnapshot(`
        Object {
          "properties": Object {
            "studentUniqueId": Object {
              "maxLength": 30,
              "minLength": 20,
              "type": "string",
            },
          },
          "required": Array [
            "studentUniqueId",
          ],
          "type": "object",
        }
      `);
      trackedChangeSchemaNames.forEach((schemaName: string) => {
        const serializedSchema: string = JSON.stringify(fragment.components.schemas[schemaName]);

        expect(schemaName).not.toContain('_readable');
        expect(schemaName).not.toContain('_writable');
        expect(serializedSchema).not.toContain('_readable');
        expect(serializedSchema).not.toContain('_writable');
        expect(serializedSchema).not.toContain('active');
        expect(serializedSchema).not.toContain('_etag');
        expect(serializedSchema).not.toContain('_lastModifiedDate');
      });
    });

    it('should not create a descriptors fragment for domain entities', () => {
      const student = namespace.entity.domainEntity.get('Student');
      const studentApiData = student.data.edfiApiSchema;
      const fragment = studentApiData.openApiFragments[OpenApiDocumentType.DESCRIPTORS];

      expect(fragment).toBeUndefined();
    });
  });

  describe('when creating a resource fragment without public tracked-change key metadata', () => {
    it('should fail rather than omit tracked-change paths', () => {
      expect(() => createResourceFragment(concreteResourceWithoutPublicTrackedChangeKeyMetadata())).toThrow(
        'Unable to create tracked-change key schema for EdFi.Student. Missing public query field mapping for identity JSON path(s): $.studentUniqueId.',
      );
    });
  });

  describe('when enhancing a descriptor', () => {
    const metaEd: MetaEdEnvironment = newMetaEdEnvironment();
    metaEd.plugin.set('edfiApiSchema', newPluginEnvironment());
    const namespaceName = 'EdFi';
    const descriptorName = 'GradeLevel';
    let namespace: any = null;

    beforeAll(() => {
      MetaEdTextBuilder.build()
        .withBeginNamespace(namespaceName)
        .withStartDescriptor(descriptorName)
        .withDocumentation('Grade level descriptor')
        .withEndDescriptor()
        .withEndNamespace()
        .sendToListener(new NamespaceBuilder(metaEd, []))
        .sendToListener(new DescriptorBuilder(metaEd, []));

      descriptorReferenceEnhancer(metaEd);
      runPrerequisiteEnhancers(metaEd);
      enhance(metaEd);

      namespace = metaEd.namespace.get(namespaceName);
    });

    it('should create a descriptors fragment', () => {
      const descriptor = namespace.entity.descriptor.get('GradeLevel');
      const descriptorApiData = descriptor.data.edfiApiSchema;
      const fragment = descriptorApiData.openApiFragments[OpenApiDocumentType.DESCRIPTORS];

      expect(fragment).toBeDefined();
      expect(fragment?.components?.schemas).toBeDefined();
      expect(fragment?.components?.schemas?.EdFi_GradeLevelDescriptor).toBeDefined();
      expect(fragment?.paths).toBeDefined();
      expect(fragment?.paths?.['/ed-fi/gradeLevelDescriptors']).toBeDefined();
      expect(fragment?.paths?.['/ed-fi/gradeLevelDescriptors/deletes']).toBeDefined();
      expect(fragment?.paths?.['/ed-fi/gradeLevelDescriptors/keyChanges']).toBeDefined();
      expect(fragment?.tags).toBeDefined();
      expect(fragment?.tags).toHaveLength(1);
      expect(fragment?.tags?.[0].name).toBe('gradeLevelDescriptors');

      const serializedFragment: string = JSON.stringify(fragment);
      expect(serializedFragment).not.toContain('Use-Snapshot');
      expect(serializedFragment).not.toContain('NotFoundUseSnapshot');
      expect(serializedFragment).not.toContain('snapshot');
      expect(fragment?.paths?.['/ed-fi/gradeLevelDescriptors']?.get?.responses['404']).toEqual({
        $ref: '#/components/responses/NotFound',
      });
      expect(fragment?.paths?.['/ed-fi/gradeLevelDescriptors/{id}']?.get?.responses['404']).toEqual({
        $ref: '#/components/responses/NotFound',
      });
      expect(fragment?.paths?.['/ed-fi/gradeLevelDescriptors']?.post?.responses['405']).toEqual({
        description: 'Method Is Not Allowed.',
      });
      expect(fragment?.paths?.['/ed-fi/gradeLevelDescriptors/{id}']?.put?.responses['405']).toEqual({
        description: 'Method Is Not Allowed.',
      });
      expect(fragment?.paths?.['/ed-fi/gradeLevelDescriptors/{id}']?.delete?.responses['405']).toEqual({
        description: 'Method Is Not Allowed.',
      });
    });

    it('should add live Change Query filters only to the descriptor GET-many operation', () => {
      const descriptor = namespace.entity.descriptor.get('GradeLevel');
      const descriptorApiData = descriptor.data.edfiApiSchema;
      const fragment = descriptorApiData.openApiFragments[OpenApiDocumentType.DESCRIPTORS] as OpenApiFragment;

      expectLiveChangeVersionFilterParameters(operationFrom(fragment, '/ed-fi/gradeLevelDescriptors', 'get'));
      expectNoLiveChangeVersionFilterParameters(operationFrom(fragment, '/ed-fi/gradeLevelDescriptors', 'post'));
      expectNoLiveChangeVersionFilterParameters(operationFrom(fragment, '/ed-fi/gradeLevelDescriptors/{id}', 'get'));
      expectNoLiveChangeVersionFilterParameters(operationFrom(fragment, '/ed-fi/gradeLevelDescriptors/{id}', 'put'));
      expectNoLiveChangeVersionFilterParameters(operationFrom(fragment, '/ed-fi/gradeLevelDescriptors/{id}', 'delete'));
    });

    it('should add tracked-change delete and key-change paths with descriptor response schemas', () => {
      const descriptor = namespace.entity.descriptor.get('GradeLevel');
      const descriptorApiData = descriptor.data.edfiApiSchema;
      const fragment = descriptorApiData.openApiFragments[OpenApiDocumentType.DESCRIPTORS] as OpenApiFragment;

      expectTrackedChangeOperation(
        operationFrom(fragment, '/ed-fi/gradeLevelDescriptors/deletes', 'get'),
        'EdFi_GradeLevelDescriptor_TrackedChangeDelete',
      );
      expectTrackedChangeOperation(
        operationFrom(fragment, '/ed-fi/gradeLevelDescriptors/keyChanges', 'get'),
        'EdFi_GradeLevelDescriptor_TrackedChangeKeyChange',
      );
    });

    it('should not create a resources fragment for descriptors', () => {
      const descriptor = namespace.entity.descriptor.get('GradeLevel');
      const descriptorApiData = descriptor.data.edfiApiSchema;
      const fragment = descriptorApiData.openApiFragments[OpenApiDocumentType.RESOURCES];

      expect(fragment).toBeUndefined();
    });
  });

  describe('when enhancing a school year enumeration', () => {
    const metaEd: MetaEdEnvironment = newMetaEdEnvironment();
    metaEd.plugin.set('edfiApiSchema', newPluginEnvironment());
    const namespaceName = 'EdFi';
    let namespace: Namespace;

    beforeAll(() => {
      MetaEdTextBuilder.build()
        .withBeginNamespace(namespaceName)
        .withStartEnumeration('SchoolYear')
        .withDocumentation('School year')
        .withEnumerationItem('2022')
        .withEndEnumeration()
        .withEndNamespace()
        .sendToListener(new NamespaceBuilder(metaEd, []))
        .sendToListener(new EnumerationBuilder(metaEd, []));

      runPrerequisiteEnhancers(metaEd);
      enhance(metaEd);

      namespace = metaEd.namespace.get(namespaceName) as Namespace;
    });

    it('should add live Change Query filters to the SchoolYearType GET-many operation', () => {
      const schoolYear = namespace.entity.schoolYearEnumeration.get('SchoolYear') as SchoolYearEnumeration;
      const schoolYearApiData = schoolYear.data.edfiApiSchema;
      const fragment = schoolYearApiData.openApiFragments[OpenApiDocumentType.RESOURCES] as OpenApiFragment;

      expectLiveChangeVersionFilterParameters(operationFrom(fragment, '/ed-fi/schoolYearTypes', 'get'));
    });

    it('should add tracked-change delete and key-change paths to SchoolYearType', () => {
      const schoolYear = namespace.entity.schoolYearEnumeration.get('SchoolYear') as SchoolYearEnumeration;
      const schoolYearApiData = schoolYear.data.edfiApiSchema;
      const fragment = schoolYearApiData.openApiFragments[OpenApiDocumentType.RESOURCES] as OpenApiFragment;

      expectTrackedChangeOperation(
        operationFrom(fragment, '/ed-fi/schoolYearTypes/deletes', 'get'),
        'EdFi_SchoolYear_TrackedChangeDelete',
      );
      expectTrackedChangeOperation(
        operationFrom(fragment, '/ed-fi/schoolYearTypes/keyChanges', 'get'),
        'EdFi_SchoolYear_TrackedChangeKeyChange',
      );
    });
  });

  describe('when enhancing an abstract domain entity', () => {
    const metaEd: MetaEdEnvironment = newMetaEdEnvironment();
    metaEd.plugin.set('edfiApiSchema', newPluginEnvironment());
    const namespaceName = 'EdFi';
    const domainEntityName = 'EducationOrganization';
    let namespace: any = null;

    beforeAll(() => {
      MetaEdTextBuilder.build()
        .withBeginNamespace(namespaceName)
        .withStartAbstractEntity(domainEntityName)
        .withDocumentation('Base education organization')
        .withIntegerIdentity('EducationOrganizationId', 'doc')
        .withEndAbstractEntity()
        .withEndNamespace()
        .sendToListener(new NamespaceBuilder(metaEd, []))
        .sendToListener(new DomainEntityBuilder(metaEd, []));

      domainEntityReferenceEnhancer(metaEd);
      runPrerequisiteEnhancers(metaEd);
      enhance(metaEd);

      namespace = metaEd.namespace.get(namespaceName);
    });

    it('should create a fragment with schemas but no paths or tags', () => {
      const abstractEntity = namespace.entity.domainEntity.get('EducationOrganization');
      const entityApiData = abstractEntity.data.edfiApiSchema;
      const fragment = entityApiData.openApiFragments?.[OpenApiDocumentType.RESOURCES];

      expect(fragment).toBeDefined();
      expect(fragment?.components?.schemas).toBeDefined();
      expect(fragment?.components?.schemas?.EdFi_EducationOrganization).toBeDefined();
      // Abstract entities have no paths or tags
      expect(fragment?.paths).toBeUndefined();
      expect(fragment?.tags).toBeUndefined();
    });
  });

  describe('when enhancing a concrete abstract resource subclass', () => {
    const metaEd: MetaEdEnvironment = newMetaEdEnvironment();
    metaEd.plugin.set('edfiApiSchema', newPluginEnvironment());
    const namespaceName = 'EdFi';
    let namespace: Namespace;

    beforeAll(() => {
      MetaEdTextBuilder.build()
        .withBeginNamespace(namespaceName)
        .withStartAbstractEntity('EducationOrganization')
        .withDocumentation('Base education organization')
        .withIntegerIdentity('EducationOrganizationId', 'doc')
        .withEndAbstractEntity()
        .withStartDomainEntitySubclass('School', 'EducationOrganization')
        .withDocumentation('A school')
        .withIntegerIdentityRename('SchoolId', 'EducationOrganizationId', 'doc')
        .withEndDomainEntitySubclass()
        .withEndNamespace()
        .sendToListener(new NamespaceBuilder(metaEd, []))
        .sendToListener(new DomainEntityBuilder(metaEd, []))
        .sendToListener(new DomainEntitySubclassBuilder(metaEd, []));

      domainEntityReferenceEnhancer(metaEd);
      domainEntitySubclassBaseClassEnhancer(metaEd);
      runPrerequisiteEnhancers(metaEd);
      enhance(metaEd);

      namespace = metaEd.namespace.get(namespaceName) as Namespace;
    });

    it('should add tracked-change delete and key-change paths to concrete subclass endpoints', () => {
      const school = namespace.entity.domainEntitySubclass.get('School') as TopLevelEntity;
      const schoolApiData = school.data.edfiApiSchema;
      const fragment = schoolApiData.openApiFragments[OpenApiDocumentType.RESOURCES] as OpenApiFragment;

      expectTrackedChangeOperation(
        operationFrom(fragment, '/ed-fi/schools/deletes', 'get'),
        'EdFi_School_TrackedChangeDelete',
      );
      expectTrackedChangeOperation(
        operationFrom(fragment, '/ed-fi/schools/keyChanges', 'get'),
        'EdFi_School_TrackedChangeKeyChange',
      );
    });
  });

  describe('when ApiSchemaBuildingEnhancer runs after fragments are created', () => {
    const metaEd: MetaEdEnvironment = newMetaEdEnvironment();
    metaEd.plugin.set('edfiApiSchema', newPluginEnvironment());
    const namespaceName = 'EdFi';
    const domainEntityName = 'School';
    let namespace: any = null;

    beforeAll(() => {
      MetaEdTextBuilder.build()
        .withBeginNamespace(namespaceName)
        .withStartDomainEntity(domainEntityName)
        .withDocumentation('A school')
        .withIntegerIdentity('SchoolId', 'doc')
        .withEndDomainEntity()
        .withEndNamespace()
        .sendToListener(new NamespaceBuilder(metaEd, []))
        .sendToListener(new DomainEntityBuilder(metaEd, []));

      domainEntityReferenceEnhancer(metaEd);
      runPrerequisiteEnhancers(metaEd);
      enhance(metaEd);

      // Now run apiSchemaBuildingEnhancer after fragments are created
      apiSchemaBuildingEnhancer(metaEd);

      namespace = metaEd.namespace.get(namespaceName);
    });

    it('should copy openApiFragments from entity data to ResourceSchema', () => {
      const namespaceEdfiApiSchema = namespace.data.edfiApiSchema as NamespaceEdfiApiSchema;
      const { resourceSchemas } = namespaceEdfiApiSchema.apiSchema.projectSchema;

      // Find the school resource schema
      const schoolResourceSchema = Object.values(resourceSchemas).find((schema) => schema.resourceName === 'School');

      expect(schoolResourceSchema).toBeDefined();
      expect(schoolResourceSchema?.openApiFragments).toBeDefined();
      expect(schoolResourceSchema?.openApiFragments?.[OpenApiDocumentType.RESOURCES]).toBeDefined();

      // Verify the fragments contain the expected data
      const fragment = schoolResourceSchema?.openApiFragments?.[OpenApiDocumentType.RESOURCES];
      expect(fragment?.components?.schemas?.EdFi_School).toBeDefined();
      expect(fragment?.paths?.['/ed-fi/schools']).toBeDefined();
      expect(fragment?.tags?.[0].name).toBe('schools');
    });
  });

  describe('when enhancing an extension entity', () => {
    const metaEd: MetaEdEnvironment = newMetaEdEnvironment();
    metaEd.plugin.set('edfiApiSchema', newPluginEnvironment());
    const coreNamespaceName = 'EdFi';
    const extensionNamespaceName = 'SampleExtension';
    const domainEntityName = 'Student';
    let extensionNamespace: any = null;

    beforeAll(() => {
      // Create core entity
      MetaEdTextBuilder.build()
        .withBeginNamespace(coreNamespaceName)
        .withStartDomainEntity(domainEntityName)
        .withDocumentation('A student')
        .withStringIdentity('StudentUniqueId', 'doc', '30', '20')
        .withEndDomainEntity()
        .withEndNamespace()
        .sendToListener(new NamespaceBuilder(metaEd, []))
        .sendToListener(new DomainEntityBuilder(metaEd, []));

      // Create extension
      MetaEdTextBuilder.build()
        .withBeginNamespace(extensionNamespaceName)
        .withStartDomainEntityExtension(domainEntityName)
        .withDocumentation('Student extension')
        .withBooleanProperty('IsGifted', 'Is gifted', false, false)
        .withEndDomainEntityExtension()
        .withEndNamespace()
        .sendToListener(new NamespaceBuilder(metaEd, []))
        .sendToListener(new DomainEntityExtensionBuilder(metaEd, []));

      const coreNamespace = metaEd.namespace.get(coreNamespaceName);
      extensionNamespace = metaEd.namespace.get(extensionNamespaceName);

      // Mark as extension by adding dependency
      extensionNamespace.dependencies.push(coreNamespace);

      domainEntityReferenceEnhancer(metaEd);
      domainEntityExtensionBaseClassEnhancer(metaEd);
      runPrerequisiteEnhancers(metaEd);
      enhance(metaEd);
    });

    it('should create extension fragments on entity data', () => {
      // Get the extension entity - it's named "Student" in the extension namespace
      const studentExtension = extensionNamespace.entity.domainEntityExtension.get('Student');
      expect(studentExtension).toBeDefined();

      // Check that the extension fragment is stored on the entity data
      const entityApiData = studentExtension.data.edfiApiSchema;
      expect(entityApiData.openApiFragments).toBeDefined();
      expect(entityApiData.openApiFragments.resources).toBeDefined();

      const fragment = entityApiData.openApiFragments.resources;
      expect(fragment).toBeDefined();
      expect(fragment?.components?.schemas).toBeDefined();

      // Extension with no real collected properties should not produce exts
      expect(fragment?.exts).toBeUndefined();
    });

    it('should not add standalone live Change Query filters for resource extension overlays', () => {
      const studentExtension = extensionNamespace.entity.domainEntityExtension.get('Student');
      const entityApiData = studentExtension.data.edfiApiSchema;
      const fragment = entityApiData.openApiFragments.resources;

      expect(fragment?.paths).toBeUndefined();
      expect(JSON.stringify(fragment)).not.toContain('minChangeVersion');
      expect(JSON.stringify(fragment)).not.toContain('maxChangeVersion');
    });
  });

  describe('when enhancing extension-defined top-level entities', () => {
    const metaEd: MetaEdEnvironment = newMetaEdEnvironment();
    metaEd.plugin.set('edfiApiSchema', newPluginEnvironment());
    const coreNamespaceName = 'EdFi';
    const extensionNamespaceName = 'SampleExtension';
    let extensionNamespace: Namespace;

    beforeAll(() => {
      MetaEdTextBuilder.build()
        .withBeginNamespace(coreNamespaceName)
        .withStartDomainEntity('School')
        .withDocumentation('A school')
        .withIntegerIdentity('SchoolId', 'doc')
        .withEndDomainEntity()
        .withEndNamespace()
        .sendToListener(new NamespaceBuilder(metaEd, []))
        .sendToListener(new DomainEntityBuilder(metaEd, []));

      MetaEdTextBuilder.build()
        .withBeginNamespace(extensionNamespaceName, extensionNamespaceName)
        .withStartDomainEntity('BusRoute')
        .withDocumentation('A bus route')
        .withIntegerIdentity('BusRouteId', 'doc')
        .withEndDomainEntity()
        .withStartDescriptor('TransportationMode')
        .withDocumentation('Transportation mode descriptor')
        .withEndDescriptor()
        .withEndNamespace()
        .sendToListener(new NamespaceBuilder(metaEd, []))
        .sendToListener(new DomainEntityBuilder(metaEd, []))
        .sendToListener(new DescriptorBuilder(metaEd, []));

      const coreNamespace = metaEd.namespace.get(coreNamespaceName) as Namespace;
      extensionNamespace = metaEd.namespace.get(extensionNamespaceName) as Namespace;
      extensionNamespace.dependencies.push(coreNamespace);

      domainEntityReferenceEnhancer(metaEd);
      descriptorReferenceEnhancer(metaEd);
      runPrerequisiteEnhancers(metaEd);
      enhance(metaEd);
    });

    it('should add live Change Query filters to extension-defined resource GET-many operations', () => {
      const busRoute = extensionNamespace.entity.domainEntity.get('BusRoute') as TopLevelEntity;
      const busRouteApiData = busRoute.data.edfiApiSchema;
      const fragment = busRouteApiData.openApiFragments[OpenApiDocumentType.RESOURCES] as OpenApiFragment;

      expectLiveChangeVersionFilterParameters(operationFrom(fragment, '/sample-extension/busRoutes', 'get'));
    });

    it('should add tracked-change paths to extension-defined resource operations', () => {
      const busRoute = extensionNamespace.entity.domainEntity.get('BusRoute') as TopLevelEntity;
      const busRouteApiData = busRoute.data.edfiApiSchema;
      const fragment = busRouteApiData.openApiFragments[OpenApiDocumentType.RESOURCES] as OpenApiFragment;
      const trackedChangeSchemaNames: string[] = Object.keys(fragment.components.schemas)
        .filter((schemaName: string) => schemaName.includes('_TrackedChange'))
        .sort();

      expectTrackedChangeOperation(
        operationFrom(fragment, '/sample-extension/busRoutes/deletes', 'get'),
        'SampleExtension_BusRoute_TrackedChangeDelete',
      );
      expectTrackedChangeOperation(
        operationFrom(fragment, '/sample-extension/busRoutes/keyChanges', 'get'),
        'SampleExtension_BusRoute_TrackedChangeKeyChange',
      );
      expect(trackedChangeSchemaNames).toEqual([
        'SampleExtension_BusRoute_TrackedChangeDelete',
        'SampleExtension_BusRoute_TrackedChangeKey',
        'SampleExtension_BusRoute_TrackedChangeKeyChange',
      ]);
      trackedChangeSchemaNames.forEach((schemaName: string) => {
        expect(schemaName).not.toContain('_readable');
        expect(schemaName).not.toContain('_writable');
      });
    });

    it('should add live Change Query filters to extension-defined descriptor GET-many operations', () => {
      const transportationMode = extensionNamespace.entity.descriptor.get('TransportationMode') as TopLevelEntity;
      const transportationModeApiData = transportationMode.data.edfiApiSchema;
      const fragment = transportationModeApiData.openApiFragments[OpenApiDocumentType.DESCRIPTORS] as OpenApiFragment;

      expectLiveChangeVersionFilterParameters(
        operationFrom(fragment, '/sample-extension/transportationModeDescriptors', 'get'),
      );
    });

    it('should add tracked-change paths to extension-defined descriptor operations', () => {
      const transportationMode = extensionNamespace.entity.descriptor.get('TransportationMode') as TopLevelEntity;
      const transportationModeApiData = transportationMode.data.edfiApiSchema;
      const fragment = transportationModeApiData.openApiFragments[OpenApiDocumentType.DESCRIPTORS] as OpenApiFragment;

      expectTrackedChangeOperation(
        operationFrom(fragment, '/sample-extension/transportationModeDescriptors/deletes', 'get'),
        'SampleExtension_TransportationModeDescriptor_TrackedChangeDelete',
      );
      expectTrackedChangeOperation(
        operationFrom(fragment, '/sample-extension/transportationModeDescriptors/keyChanges', 'get'),
        'SampleExtension_TransportationModeDescriptor_TrackedChangeKeyChange',
      );
    });
  });

  describe('when testing projectEndpointName transformation', () => {
    const metaEd: MetaEdEnvironment = newMetaEdEnvironment();
    metaEd.plugin.set('edfiApiSchema', newPluginEnvironment());
    const namespaceName = 'SpecialEducation';
    const domainEntityName = 'Student';
    let namespace: any = null;

    beforeAll(() => {
      MetaEdTextBuilder.build()
        .withBeginNamespace(namespaceName, namespaceName)
        .withStartDomainEntity(domainEntityName)
        .withDocumentation('A student')
        .withStringIdentity('StudentUniqueId', 'doc', '30', '20')
        .withBooleanProperty('Active', 'Is active', true, false)
        .withEndDomainEntity()
        .withEndNamespace()
        .sendToListener(new NamespaceBuilder(metaEd, []))
        .sendToListener(new DomainEntityBuilder(metaEd, []));

      domainEntityReferenceEnhancer(metaEd);
      runPrerequisiteEnhancers(metaEd);
      enhance(metaEd);

      namespace = metaEd.namespace.get(namespaceName);
    });

    it('should create paths with special-education endpoint prefix', () => {
      const student = namespace.entity.domainEntity.get('Student');
      const studentApiData = student.data.edfiApiSchema;
      const fragment = studentApiData.openApiFragments[OpenApiDocumentType.RESOURCES];

      expect(fragment).toBeDefined();
      expect(fragment?.paths).toBeDefined();
      expect(fragment?.paths?.['/special-education/students']).toBeDefined();
      expect(fragment?.paths?.['/special-education/students/{id}']).toBeDefined();
    });
  });
});
