name: API Schema Packaging and Publishing

on:
  #For Testing purposes only, this need to
  pull_request:
    branches:
      - main      
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: Run the build with tmate debugging enabled
        required: true
        default: "false"
        type: choice
        options:
          - "false"
          - "true"

jobs:
  api-schema-packagin:
    name: API Schema Packaging
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Download and Unzip files
        run: ./eng/ApiSchema/build.ps1 Unzip

      - name: Run Build
        run: ./eng/ApiSchema/build.ps1 Build
      
      - name: API Schema Package
        run: ./eng/ApiSchema/build.ps1 Package "1.0.${{ github.run_number }}"
      
      - name: Publish Package
        run: ./eng/ApiSchema/build.ps1 BuildAndPublish "1.0.${{ github.run_number }}"

      - name: Upload Package as Artifact
        if: success()
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0  
        with:
          name: "${{ env.PACKAGE_NAME }}-NuGet"
          path: ./eng/ApiSchema/*.nupkg
          if-no-files-found: error
          retention-days: 30          
