name: API Schema Packaging and Publishing

on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: Run the build with tmate debugging enabled
        required: true
        default: "false"
        type: choice
        options:
          - "false"
          - "true"

env:
  ARTIFACTS_API_KEY: ${{ secrets.AZURE_ARTIFACTS_PERSONAL_ACCESS_TOKEN }}
  ARTIFACTS_FEED_URL: ${{ vars.AZURE_ARTIFACTS_FEED_URL }}
  VSS_NUGET_EXTERNAL_FEED_ENDPOINTS: '{"endpointCredentials": [{"endpoint": "${{ vars.AZURE_ARTIFACTS_FEED_URL }}","password": "${{ secrets.AZURE_ARTIFACTS_PERSONAL_ACCESS_TOKEN }}"}]}'

jobs:
  run-metaed-project:
    name: Run MetaEd Project
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Run MetaEd Project
        run: ./eng/ApiSchema/build.ps1 RunMetaEd

      - name: Upload MetaEdOutput as Artifact
        if: success()
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: "MetaEdOutput"
          path: ./MetaEdOutput
          if-no-files-found: error
          retention-days: 5

  api-schema-packaging:
    name: API Schema Packaging
    runs-on: ubuntu-latest
    needs: run-metaed-project
    defaults:
      run:
        shell: pwsh
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Get Artifacts
        uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 #v4.1.1
        with:
          name: MetaEdOutput
          path: ./MetaEdOutput

      - name: Display structure of downloaded files

        run: ls -R ./

      - name: Download and Unzip files
        run: ./eng/ApiSchema/build.ps1 Unzip

      - name: Move MetaEd ApiSchema Files
        run: ./eng/ApiSchema/build.ps1 MoveMetaEdSchema

      - name: Run Build
        run: ./eng/ApiSchema/build.ps1 Build

      - name: API Schema Package - Create NuGet File
        run: ./eng/ApiSchema/build.ps1 Package "1.0.${{ github.run_number }}"

      - name: Publish Package
        run: ./eng/ApiSchema/build.ps1 BuildAndPublish "1.0.${{ github.run_number }}"

      - name: Upload Package as Artifact
        if: success()
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8 # v4.3.0
        with:
          name: "EdFi.ApiSchema-NuGet.1.0.${{ github.run_number }}"
          path: ./eng/ApiSchema/*.nupkg
          if-no-files-found: error
          retention-days: 30

  publish-package:
    name: Publish NuGet Package
    needs: api-schema-packaging
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: pwsh
    steps:
      - uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: Get Artifact
        uses: actions/download-artifact@6b208ae046db98c579e8a3aa621ab581ff575935 #4.1.1
        with:
          name: EdFi.ApiSchema-NuGet.1.0.${{ github.run_number }}

      - name: Install-credential-handler
        run: iex "& { $(irm https://aka.ms/install-artifacts-credprovider.ps1) } -AddNetfx"

      - name: Push Package to Azure Artifacts
        run: |
          $packageDir = "/home/runner/work/MetaEd-js/MetaEd-js"
          $artifacts = (Get-ChildItem -Path $packageDir -Name -Include *.nupkg)

           echo "Artifacts List"
           echo $artifacts

          $arguments = @{
            NuGetApiKey = "${{ env.ARTIFACTS_API_KEY }}"
            EdFiNuGetFeed = "${{ env.ARTIFACTS_FEED_URL }}"
          }

          if ($artifacts.Count -eq 0) {
           throw "Cannot find a NuGet package $packageDir"
          } 
          else {
             $artifacts | ForEach-Object {
                 echo "Package Files"             
                 $arguments.PackageFile = Join-Path -Path $packageDir -ChildPath $_
                 echo $arguments.PackageFile
                 ./eng/ApiSchema/build.ps1 PushPackage @arguments
               }
          }
