name: Auto Publish Dev
on:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  auto-publish-dev:
    name: Auto Publish Dev

    # Only if closed due to merge
    if: github.event.pull_request.merged == true

    # Windows is required for some of the unit tests to run properly
    runs-on: ubuntu-20.04
    
    steps:
      - name: Checkout code   
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0
        
      - name: Lint and Test
        uses: ./.github/actions/lint-and-test-metaed

      - name: Build
        run: yarn build
      
      - name: Import GPG key
        id: import-gpg
        uses: crazy-max/ghaction-import-gpg@cb4264d3319acaa2bea23d51ef67f80b4f775013 # v4.1.0
        with:
          gpg_private_key: ${{ secrets.EDFIBUILDAGENT_PRIVATE_KEY }}
          passphrase: ${{ secrets.EDFIBUILDAGENT_PASSPHRASE }}
          git_user_signingkey: true
          git_commit_gpgsign: true

      - name: Publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_MYGET_ACCESS_TOKEN }}
        run: |
          git config user.name "${{ steps.import-gpg.outputs.name }}"
          git config user.email "${{ steps.import-gpg.outputs.email }}"

          yarn lerna version prerelease --exact --force-publish=* --force-git-tag --sign-git-commit --yes --preid=dev

          yarn lerna publish from-git --yes --dist-tag=dev --no-verify-access
