name: Lint and Test
on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
jobs:
  lint-and-test:
    name: Run Lint and Unit Tests
    # Windows is required for some of the unit tests to run properly
    runs-on: windows-2019
    steps:
      - name: Checkout code
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f

      - name: Setup node
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561
        with:
          node-version: '16'
          check-latest: true
          registry-url: 'https://www.myget.org/F/ed-fi/npm/'

      - name: Install
        run: yarn install

      - name: Lint
        run: yarn test:lint

      - name: Unit tests
        run: yarn test:unit:ci --ci
