name: Lint and Test
on:
  workflow_dispatch:
  pull_request:
jobs:
  lint-and-test:
    name: Lint and Test
    # Windows is required for some of the unit tests to run properly
    runs-on: windows-2019
    steps:
      - uses: ./.github/actions/lint-test-metaed
