name: Lint and Test
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
          description: Run the build with tmate debugging enabled
          required: true
          default: 'false'
          type: choice
          options:
          - false
          - true
jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
