name: Lint and Test
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
          description: Run the build with tmate debugging enabled
          required: true
          default: 'false'
          type: choice
          options:
          - false
          - true

  pull_request:
jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-20.04
    steps:        
      - name: Checkout code   
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Set up Node
        uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561 # v2.5.1
        with:
          node-version: '16'
          check-latest: true
          registry-url: 'https://www.myget.org/F/ed-fi/npm/'

      - name: Install
        run: yarn install
        shell: bash

      # Enable tmate debugging if the input option was provided (https://github.com/marketplace/actions/debugging-with-tmate)
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@8b4e4ac71822ed7e0ad5fb3d1c33483e9e8fb270 # v3.1.1
  