name: Lint and Test
on:
  workflow_dispatch:
  pull_request:
jobs:
  lint-and-test:
    name: Lint and Test
    runs-on: ubuntu-20.04
    steps:        
      - name: Checkout code   
        uses: actions/checkout@ec3a7ce113134d7a93b817d10a8272cb61118579 # v2.4.0

      - name: Lint and Test
        uses: ./.github/actions/lint-and-test-metaed
