name: Dependency Review

on:
  pull_request:
    branches:
      - main
    paths:
      - "packages/**"
      - ".github"

jobs:
  scan-actions:
    name: Scan Actions
    uses: ed-fi-alliance-oss/ed-fi-actions/.github/workflows/repository-scanner.yml@latest

  analyze-code:
    name: Analyze Code Dependencies
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b # v3.0.2

      - name: Dependency Review ("Dependabot on PR")
        uses: actions/dependency-review-action@11310527b429536e263dc6cc47873e608189ba21 # v3.0.1
