name: NuGet Package Creation for API Schema and XSD Files
on:
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: Run the build with tmate debugging enabled
        required: true
        default: "false"
        type: choice
        options:
          - "false"
          - "true"

jobs:
  nuget-package-creation:
    name: Nuget Package Creation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1

      - name: List repository
        shell: pwsh
        run: |
          ls
      - name: Unzip Files
        shell: pwsh
        run: ./eng/ApiSchema/build.ps1 Unzip

      - name: Run Build
        run: ./eng/ApiSchema/build.ps1 Build
      
      #- name: Package
      #  run: ./eng/ApiSchema/build.ps1 Package
      
      #- name: Publish Package
      #  run: ./eng/ApiSchema/build.ps1 Publish
