name: Publish Dev Version
on:
  workflow_dispatch:
    debug_enabled:
      description: Run the build with tmate debugging enabled     
      required: true
      default: 'false'
      type: choice
      options:
      - false
      - true

  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  publish-dev:
    name: Publish Dev

    # Only if closed due to merge or manual trigger
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'

    uses: Ed-Fi-Closed/MetaEd-js/.github/workflows/reusable-publish.yml@main
    with:
      bump: dev
      # '|| false' below handles pull_request event case, where github.event.inputs.debug_enabled is undefined
      debug_enabled: ${{ github.event.inputs.debug_enabled || 'false' }}

    secrets:
      EDFI_BUILD_AGENT_PAT: ${{ secrets.EDFI_BUILD_AGENT_PAT }}
      EDFIBUILDAGENT_PRIVATE_KEY: ${{ secrets.EDFIBUILDAGENT_PRIVATE_KEY }}
      EDFIBUILDAGENT_PASSPHRASE: ${{ secrets.EDFIBUILDAGENT_PASSPHRASE }}
      NPM_MYGET_ACCESS_TOKEN: ${{ secrets.NPM_MYGET_ACCESS_TOKEN }}
