name: Publish Dev Version
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: Run the build with tmate debugging enabled
        required: true
        default: "false"
        type: choice
        options:
          - "false"
          - "true"

  pull_request:
    types: [closed]
    branches:
      - main

jobs:
  publish-dev:
    name: Publish Dev

    # Only if closed due to merge or manual trigger
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'

    uses: ./.github/workflows/reusable-publish.yml
    with:
      bump: dev
      # '|| false' below handles pull_request event case, where github.event.inputs.debug_enabled is undefined
      debug_enabled: ${{ github.event.inputs.debug_enabled || 'false' }}

    secrets:
      EDFI_BUILD_AGENT_PAT: ${{ secrets.EDFI_BUILD_AGENT_PAT }}
      EDFIBUILDAGENT_PRIVATE_KEY: ${{ secrets.EDFIBUILDAGENT_PRIVATE_KEY }}
      EDFIBUILDAGENT_PASSPHRASE: ${{ secrets.EDFIBUILDAGENT_PASSPHRASE }}
      AZURE_ARTIFACTS_PERSONAL_ACCESS_TOKEN : ${{ secrets.AZURE_ARTIFACTS_PERSONAL_ACCESS_TOKEN  }}
