name: Publish Release
on:
  workflow_dispatch:
    inputs:
      bump:
        description: "Version Bump"
        required: true
        default: "patch"
        type: choice
        options:
          - major
          - minor
          - patch

      debug_enabled:
        description: Run the build with tmate debugging enabled
        required: true
        default: "false"
        type: choice
        options:
          - "false"
          - "true"

jobs:
  publish-major:
    name: Publish Release

    uses: Ed-Fi-Closed/MetaEd-js/.github/workflows/reusable-publish.yml@main
    with:
      bump: ${{ github.event.inputs.bump }}
      debug_enabled: ${{ github.event.inputs.debug_enabled }}
    secrets:
      EDFI_BUILD_AGENT_PAT: ${{ secrets.EDFI_BUILD_AGENT_PAT }}
      EDFIBUILDAGENT_PRIVATE_KEY: ${{ secrets.EDFIBUILDAGENT_PRIVATE_KEY }}
      EDFIBUILDAGENT_PASSPHRASE: ${{ secrets.EDFIBUILDAGENT_PASSPHRASE }}
      NPM_MYGET_ACCESS_TOKEN: ${{ secrets.NPM_MYGET_ACCESS_TOKEN }}
