name: Publish Dev Version
on:
  workflow_dispatch:
  pull_request:
    types: [closed]
    branches:
      - main
jobs:
  publish-dev:
    name: Publish Dev

    # Only if closed due to merge or manual trigger
    if: github.event.pull_request.merged == true || github.event_name == 'workflow_dispatch'

    uses: Ed-Fi-Closed/MetaEd-js/.github/workflows/reusable-publish.yml@main
    with:
      bump: dev
