name: Publish Release
on:
  workflow_dispatch:
    inputs:
      bump:
        description: 'Version Bump'
        required: true
        default: 'patch' 
        type: choice
        options:
        - major
        - minor
        - patch

jobs:
  publish-major:
    name: Publish Release

    uses: Ed-Fi-Closed/MetaEd-js/.github/workflows/reusable-publish.yml@main
    with:
      bump: ${{ github.event.inputs.bump }}
    secrets:
      EDFI_BUILD_AGENT_PAT: ${{ secrets.EDFI_BUILD_AGENT_PAT }}
      EDFIBUILDAGENT_PRIVATE_KEY: ${{ secrets.EDFIBUILDAGENT_PRIVATE_KEY }}
      EDFIBUILDAGENT_PASSPHRASE: ${{ secrets.EDFIBUILDAGENT_PASSPHRASE }}
      NPM_MYGET_ACCESS_TOKEN: ${{ secrets.NPM_MYGET_ACCESS_TOKEN }}
