name: Publish Major Version
on:
  workflow_dispatch:

jobs:
  publish-major:
    name: Publish Major

    uses: Ed-Fi-Closed/MetaEd-js/.github/workflows/reusable-publish.yml@main
    with:
      bump: major
    secrets:
      EDFI_BUILD_AGENT_PAT: ${{ secrets.EDFI_BUILD_AGENT_PAT }}
      EDFIBUILDAGENT_PRIVATE_KEY: ${{ secrets.EDFIBUILDAGENT_PRIVATE_KEY }}
      EDFIBUILDAGENT_PASSPHRASE: ${{ secrets.EDFIBUILDAGENT_PASSPHRASE }}
      NPM_MYGET_ACCESS_TOKEN: ${{ secrets.NPM_MYGET_ACCESS_TOKEN }}
