name: Build and Publish
on:
  workflow_dispatch:
    # All input comes from secrets
jobs:
  build-and-publish:
    name: Build and publish
    # Must run on Windows
    runs-on: windows-2019
    steps:
      - name: Checkout code   
        uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
        
      - uses: actions/setup-node@1f8c6b94b26d0feae1e387ca63ccbdc44d27b561
        with:
          node-version: '16'
          registry-url: 'https://www.myget.org/F/ed-fi/npm/'

      - name: Install
        run: yarn install
      
      - name: Build
        run: yarn build

      - name: Publish
        run: yarn publish-all
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_MYGET_ACCESS_TOKEN }}
