
name: Semgrep Code Analysis Spike
on:
  workflow_dispatch:

jobs:
  semgrep:
    name: Run Semgrep
    runs-on: ubuntu
    steps:
      - name: Checkout repository
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b # v3.2.0
      
      - name: Run Semgrep in a container
        run: docker run --rm -v "${PWD}:/src" returntocorp/semgrep semgrep --config auto